name: tla-llm
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pip
  - accelerate=1.3.0
  - datasets=3.2.0
  - huggingface_hub=0.28.0
  - peft=0.14.0
  - trl=0.14.0
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.4
  - jinja2
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - pyyaml
  - aiohttp
  - attrs
  - ipython
  - ipykernel
  - pip:
      - zenml
      - zenml[server]
      - dvc[gdrive]
      - mlflow
      - langchain
      - openai
      - transformers==4.48.3
      - bitsandbytes==0.45.1
      - tiktoken==0.8.0
      - codebleu
      - javalang
      - python-dotenv
      - sympy
      - tree-sitter
      - tree-sitter-python
      - tree-sitter-java
      - tree-sitter-languages

