name: tla-llm
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - pandas
  - matplotlib
  - pip:
      - zenml
      - zenml[server]
      - dvc[gdrive]
      - mlflow
      - langchain-core
      - langchain-community
      - langchain-openai
      - langchain-ollama
      - langchain-anthropic
      - openai
      - python-dotenv

